### ISSUE TITLE
../target/sap-em-pulsar-connector-1.0.0-SNAPSHOT.nar  File not found

### ISSUE THREAD

**Issue by divya-inaza** [chrsoo/sap-em-pulsar-connector#3]
Hey

I am looking for this file '../target/sap-em-pulsar-connector-1.0.0-SNAPSHOT.nar' but unable to find it.

Could you please provide me with this one?

**Comment by chrsoo** [comment]
Hi Divya,

Well this project was part of evaluating Apache Pulsar together with SAP enterprise messaging. We have since discarded both and are using Solace (the broker on which SAP Enterprise Messaging is based).

I recommend that you clone the project and build the JAR file locally. For this you need Java and Maven installed.

Please note that I am not even sure that the NAR file builds properly with more recent versions of Java... Testing locally I get warnings that I am not sure if they were there the last time when I built it three years ago...

Hopefully you get it working, feel free to fork the project and take ownership if you think it is still useful!

**Comment by divya-inaza** [comment]
Thanks for your response.
